### ISSUE TITLE
`Test-All` returns true but `Test-Any` returns false for same input

### ISSUE THREAD

**Issue by ninmonkey** [chriskuech/functional#13]
If `Test-All` is true, then `Test-Any` should automatically be true too

## Code to Reproduce

```ps1
@() | functional\Test-All
@() | functional\Test-Any
```

## Output

```ps1
@() | functional\Test-All
True
@() | functional\Test-Any
False
```

**Comment by chriskuech** [comment]
"Any" returns true if there is at least one truthy item in the collection, so Any cannot return true for an empty collection. 

"All" returns true if every item in the collection is truthy, so if there are no items in this collection then the condition is still true and All returns true for an empty collection.

Note that this follows the same definition as the native implementation in other languages like Python.
