### ISSUE TITLE
Powershell: functional: reduce: How to initialize the reduce accumulator?

### ISSUE THREAD

**Issue by jgodse** [chriskuech/functional#5]
I want to use the functional "reduce" function to calculate things, such as the factorial of a number. e.g. The factorial of 5 is 5x4x3x2x1 = 120. In Ruby I can do it with something like:

```Ruby
# factorial1.rb

(1..5).reduce{|accumulator,element| accumulator*element}
```

In Powershell I would do something like:
```PowerShell
# factorial.ps
# ------ Install this library before using the "reduce" function
# Install-Module -Name functional

1..5 | reduce {$a*$b}  

```

In both languages, the answer is 120, and the accumulator is assumed to be an integer, with an
initial value of the first element in the range.

If I redefined the factorial to have an initial value of 10, in Ruby I
would code it as

```Ruby
# factorial2.rb
# (1..5).reduce    {|accumulator,element| accumulator*element} #uninitialized accumulator
  (1..5).reduce(10){|accumulator,element| accumulator*element}
```

This yields the expected answer of 1200.

**QUESTION 1**:  How does one initialize a "reduce" accumulator in Powershell?

In the next scenario, I want to generate a list of factorials. If
I were to code it in Ruby, I could initialize the reduce accumulator
with [1] (because 0! is 1), resulting in the following code:

```Ruby
# factorial.rb
# (1..5).reduce     {|accumulator,element| accumulator*element}  #uninitialized accumulator
  (1..5).reduce([1]){|accumulator,element| accumulator << accumulator[-1]*element}

```

The output looks something like 
```
   => [1, 1, 2, 6, 24, 120]

```

**QUESTION 2**: How does one use an expandible array to initialize the accumulator for the
   Powershell "reduce" function of the "functional" module?

**Comment by chriskuech** [comment]
1. I didn't add support for an initial accumulator because it's just as easy to append a new first element:
    ```powershell
    @(10) + 1..5 | reduce {$a * $b}
    ```
2. I'm not sure what you mean by an "expandable array" (possibly a ruby term?), but the equivalent PowerShell would be:
    ```powershell
    @(,@(1)) + 1..5 | reduce {$a + $a[-1] * $b}
    ```
    In this case, PowerShell's implicit casting of arrays can cause confusion.  I added the comma to tell PowerShell not to implicitly flatten my array.

Feel free to reopen if you have any questions.
